### ISSUE TITLE
Error while scaffolding react-native typescript template

### ISSUE THREAD

**Issue by urtheaman** [jridgewell/trace-mapping#13]
error Couldn't find package "@jridgewell/resolve-uri@^3.0.3" required by "@jridgewell/trace-mapping@^0.3.9" on the "npm" registry.

**Comment by jridgewell** [comment]
This seems like a npm error? There are [several versions](https://www.npmjs.com/package/@jridgewell/resolve-uri) that satisfy the `^3.0.3` constraint.

**Comment by urtheaman** [comment]
yes, it's an npm error. later it installed all of ém. Thanks.
