### ISSUE TITLE
allGeneratedPositions doesn't find a position if GREATEST_LOWER_BOUND doesn't match

### ISSUE THREAD

**Issue by connor4312** [jridgewell/trace-mapping#22]
1. Try to resolve all generated positions on the start of this line https://github.com/microsoft/vscode-js-debug/blob/main/testWorkspace/web/browserify/module2.ts#L3 (the file is compiled in https://github.com/microsoft/vscode-js-debug/blob/main/testWorkspace/web/browserify/pause.js)
2. See that `allGeneratedPositions` returns `[]` for that location (line 3 col 0)
3. See that `generatedPosition` returns null searching with `GREATEST_LOWER_BOUND`, but returns the right position with `LEAST_UPPER_BOUND`

Apologies if I set this on the wrong track with my initial PR. I should have tried to run our suite of unit tests against the library before submitting the PR. I'll try to find some time to learn more and fix it, if you don't get to it before me.

**Comment by jridgewell** [comment]
Can you provide the sourcemap JSON and call args you're using?

**Comment by jridgewell** [comment]
I believe this is the correct behavior. Loading that map, there are no segments that span `{ line: 3, column 0 }`. The first segment on that line is at column 2, as shown by the [visualizer](https://evanw.github.io/source-map-visualization/#MTIzNwAoZnVuY3Rpb24oKXtmdW5jdGlvbiByKGUsbix0KXtmdW5jdGlvbiBvKGksZil7aWYoIW5baV0pe2lmKCFlW2ldKXt2YXIgYz0iZnVuY3Rpb24iPT10eXBlb2YgcmVxdWlyZSYmcmVxdWlyZTtpZighZiYmYylyZXR1cm4gYyhpLCEwKTtpZih1KXJldHVybiB1KGksITApO3ZhciBhPW5ldyBFcnJvcigiQ2Fubm90IGZpbmQgbW9kdWxlICciK2krIiciKTt0aHJvdyBhLmNvZGU9Ik1PRFVMRV9OT1RfRk9VTkQiLGF9dmFyIHA9bltpXT17ZXhwb3J0czp7fX07ZVtpXVswXS5jYWxsKHAuZXhwb3J0cyxmdW5jdGlvbihyKXt2YXIgbj1lW2ldWzFdW3JdO3JldHVybiBvKG58fHIpfSxwLHAuZXhwb3J0cyxyLGUsbix0KX1yZXR1cm4gbltpXS5leHBvcnRzfWZvcih2YXIgdT0iZnVuY3Rpb24iPT10eXBlb2YgcmVxdWlyZSYmcmVxdWlyZSxpPTA7aTx0Lmxlbmd0aDtpKyspbyh0W2ldKTtyZXR1cm4gb31yZXR1cm4gcn0pKCkoezE6W2Z1bmN0aW9uKHJlcXVpcmUsbW9kdWxlLGV4cG9ydHMpewoidXNlIHN0cmljdCI7CmV4cG9ydHMuX19lc01vZHVsZSA9IHRydWU7CmV4cG9ydHMua01vZHVsZTEgPSAxOwpmdW5jdGlvbiBmb28oKSB7CiAgICBkZWJ1Z2dlcjsKfQpleHBvcnRzLmZvbyA9IGZvbzsKZnVuY3Rpb24gdGhyb3dFcnJvcihzKSB7CiAgICB0aHJvdyBuZXcgRXJyb3Iocyk7Cn0KZXhwb3J0cy50aHJvd0Vycm9yID0gdGhyb3dFcnJvcjsKZnVuY3Rpb24gdGhyb3dWYWx1ZSh2KSB7CiAgICB0aHJvdyB2Owp9CmV4cG9ydHMudGhyb3dWYWx1ZSA9IHRocm93VmFsdWU7Cgp9LHt9XSwyOltmdW5jdGlvbihyZXF1aXJlLG1vZHVsZSxleHBvcnRzKXsKInVzZSBzdHJpY3QiOwpleHBvcnRzLl9fZXNNb2R1bGUgPSB0cnVlOwpleHBvcnRzLmtNb2R1bGUyID0gMjsKZnVuY3Rpb24gYmFyKGNhbGxiYWNrKSB7CiAgICBjYWxsYmFjaygpOwp9CmV4cG9ydHMuYmFyID0gYmFyOwpmdW5jdGlvbiBwYXVzZSgpIHsKICAgIGRlYnVnZ2VyOwp9CmV4cG9ydHMucGF1c2UgPSBwYXVzZTsKCn0se31dLDM6W2Z1bmN0aW9uKHJlcXVpcmUsbW9kdWxlLGV4cG9ydHMpewoidXNlIHN0cmljdCI7CmV4cG9ydHMuX19lc01vZHVsZSA9IHRydWU7CnZhciBtMSA9IHJlcXVpcmUoIi4vbW9kdWxlMSIpOwp2YXIgbTIgPSByZXF1aXJlKCIuL21vZHVsZTIiKTsKbTIuYmFyKG0xLmZvbyk7Cgp9LHsiLi9tb2R1bGUxIjoxLCIuL21vZHVsZTIiOjJ9XX0se30sWzNdKQovLyMgc291cmNlTWFwcGluZ1VSTD1wYXVzZS5qcy5tYXAKNjU0AHsidmVyc2lvbiI6Mywic291cmNlcyI6WyIuLi8uLi9ub2RlX21vZHVsZXMvYnJvd3Nlci1wYWNrL19wcmVsdWRlLmpzIiwibW9kdWxlMS50cyIsIm1vZHVsZTIudHMiLCJwYXVzZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTs7O0FDQWEsUUFBQSxRQUFRLEdBQUcsQ0FBQyxDQUFDO0FBQzFCLFNBQWdCLEdBQUc7SUFDakIsUUFBUSxDQUFDO0FBQ1gsQ0FBQztBQUZELGtCQUVDO0FBQ0QsU0FBZ0IsVUFBVSxDQUFDLENBQUM7SUFDMUIsTUFBTSxJQUFJLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQztBQUNyQixDQUFDO0FBRkQsZ0NBRUM7QUFDRCxTQUFnQixVQUFVLENBQUMsQ0FBQztJQUMxQixNQUFNLENBQUMsQ0FBQztBQUNWLENBQUM7QUFGRCxnQ0FFQzs7Ozs7QUNUWSxRQUFBLFFBQVEsR0FBRyxDQUFDLENBQUM7QUFDMUIsU0FBZ0IsR0FBRyxDQUFDLFFBQVE7SUFDMUIsUUFBUSxFQUFFLENBQUM7QUFDYixDQUFDO0FBRkQsa0JBRUM7QUFDRCxTQUFnQixLQUFLO0lBQ25CLFFBQVEsQ0FBQztBQUNYLENBQUM7QUFGRCxzQkFFQzs7Ozs7QUNORCw4QkFBZ0M7QUFDaEMsOEJBQWdDO0FBRWhDLEVBQUUsQ0FBQyxHQUFHLENBQUMsRUFBRSxDQUFDLEdBQUcsQ0FBQyxDQUFDIiwiZmlsZSI6ImdlbmVyYXRlZC5qcyIsInNvdXJjZVJvb3QiOiIifQ==)

<img width="1280" alt="Screen Shot 2022-10-11 at 5 31 15 PM" src="https://user-images.githubusercontent.com/112982/195202346-0e682695-65cb-4d99-b380-3a613b2ce33e.png">

Can you explain how you get column 0 in whatever code is calling `allGeneratedPositions`?

**Comment by jridgewell** [comment]
Oh, I'm just realizing that `source-map`'s `allGeneratedPositions` has an optional `column` field, giving you everything on that line. Is that the behavior you're looking for?

**Comment by connor4312** [comment]
> Can you explain how you get column 0 in whatever code is calling allGeneratedPositions?

This is from [a test emulating] VS Code setting a breakpoint on the line, which goes to column 0.

> Oh, I'm just realizing that source-map's allGeneratedPositions has an optional column field, giving you everything on that line. Is that the behavior you're looking for?

No, we do pass in the column -- https://github.com/microsoft/vscode-js-debug/blob/d5c755e3ae433de283b3aca8a5119e5f74566431/src/common/sourceUtils.ts#L302-L306

This is what it looks like when given to `source-map`:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/2230985/195208320-6c9835f1-0f3d-4a9a-b8dc-d27f47d1dc89.png">

I actually tried to look at [the source-map code](https://docs.rs/source-map-mappings/0.5.0/src/source_map_mappings/lib.rs.html#432-490) when first implementing it, and was very confused since it looks like it just returned all mappings on the line starting at the column... but maybe that's actually what it does. That seems wrong.

**Comment by jridgewell** [comment]
Hmm, apparently `source-map` is using `LEAST_UPPER_BOUND` to perform its search: https://github.com/mozilla/source-map/blob/0.6.1/lib/source-map-consumer.js#L208

We should be able to match that. The only time this comes up is when there's not a found match, in which case we just need to increment the index by 1.

**Comment by jridgewell** [comment]
Opened #23
