### ISSUE TITLE
`trace-mapping` source maps are broken

### ISSUE THREAD

**Issue by benmccann** [jridgewell/trace-mapping#25]
The source maps have:
`"sources":["../src/resolve.ts","../src/strip-filename.ts","../src/sourcemap-segment.ts","../src/sort.ts","../src/binary-search.ts","../src/by-source.ts","../src/any-map.ts","../src/trace-mapping.ts"]`

But there's no `src` folder in the package

**Comment by jridgewell** [comment]
The actual files shouldn't need to exist, their content is included as the `sourcesContent` on the sourcemap.

**Comment by benmccann** [comment]
Ah, I missed that. Sorry for the false report

**Comment by trmjoa** [comment]
Question/Followup here. I am trying to use the node debugger in vscode. It likes to resolve sourcemaps for typescript files and it tries to resolve these paths event though the sroucesContent section is set. It results in that the debugging session is terminated during startup with the following error:

`Could not read source map for file:///Users/me/.config/yarn/global/node_modules/%40jridgewell/trace-mapping/src/trace-mapping.ts: ENOENT: no such file or directory, open '/Users/me/.config/yarn/global/node_modules/@jridgewell/trace-mapping/src/") at the end of the child file.'`

Any known workarounds for that? The module is globally installed. I tried various ways of configuring vscode to not resolve these sourcemaps, but without any luck
