### ISSUE TITLE
The SourceNeedle is referenced in generated position methods, but is not exported

### ISSUE THREAD

**Issue by connor4312** [jridgewell/trace-mapping#31]
`all/generatedPositionFor` references the `SourceNeedle`, but this is not exported from the package root, which makes consumption a bit ugly, requiring importing from the `types` file directly if one wants to pass it through places.

**Comment by jridgewell** [comment]
I think at this point we can use [`export type * from './types'`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#support-for-export-type) so that I stop missing some of the types.

**Comment by connor4312** [comment]
That would make sense 👍 

Btw, I [finally moved](https://github.com/microsoft/vscode-js-debug/pull/1916) the vscode JS debugger over from the old `source-map` library to this one. I'm quite happy to have finally gotten that ripped out!
