### ISSUE TITLE
Error: Only named exports may use 'export type'.

### ISSUE THREAD

**Issue by lucb31** [jridgewell/trace-mapping#33]
Hi,

I just upgraded to the newest version `0.3.21` and got the following error when trying to build my project:

```
> tsc -p tsconfig.package.json

../../node_modules/@jridgewell/trace-mapping/dist/types/trace-mapping.d.ts:4:1 - error TS1383: Only named exports may use 'export type'.

4 export type * from './types';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in ../../node_modules/@jridgewell/trace-mapping/dist/types/trace-mapping.d.ts:4
```

I think it´s related to this commit https://github.com/jridgewell/trace-mapping/commit/d04e7fe0bda0952e1542dd89a6ae3ff85967346a

After downgrading back to `0.3.20` the error is gone. Any ideas?

**Comment by jridgewell** [comment]
You're probably using an older TS version? I think TS v5 added `export type *` syntax.

**Comment by karthik-sciera** [comment]
As @lucb31 comments, the error is gone when downgrading to 0.3.20.

**Comment by lucb31** [comment]
@jridgewell thanks for the fix. Works again with the most recent version. Makes sense to not rely on TS 5 syntax here IMO since quite a few other packages depend on this and none explicitly state that they require TS v5. 
Appreciate your effort!
