### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by labad123456** [jridgewell/trace-mapping#35]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @jridgewell/trace-mapping@^0.3.24.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@jridgewell/gen-mapping'
npm ERR! notarget 

with this package

{
  "description": "",
  "scripts": {
    "ng": "ng"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "7.2.13",
    "@angular/common": "7.2.13",
    "@angular/compiler": "7.2.13",
    "@angular/core": "7.2.13",
    "@angular/forms": "7.2.13",
    "@angular/http": "7.2.13",
    "@angular/platform-browser": "7.2.13",
    "@angular/platform-browser-dynamic": "7.2.13",
    "@angular/router": "7.2.13",
    "@auth0/angular-jwt": "^2.0.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@ng-bootstrap/ng-bootstrap": "^4.2.1",
    "@types/jquery": "^3.5.29",
    "bootstrap": "4.0.0",
    "cldrjs": "0.4.8",
    "core-js": "^2.6.12",
    "devextreme": "18.2.7",
    "devextreme-angular": "18.2.6",
    "devextreme-intl": "18.2.6",
    "globalize": "1.3.0",
    "gtin": "^0.3.0",
    "jquery": "3.3.1",
    "jquery-mousewheel": "3.1.13",
    "metismenu": "2.7.0",
    "moment": "^2.30.1",
    "net": "^1.0.2",
    "ng-bullet": "^1.0.3",
    "ngx-electron": "2.1.1",
    "ngx-malihu-scrollbar": "^7.0.0",
    "ngx-toastr": "^9.2.0",
    "node-sass": "^4.14.1",
    "popper.js": "1.15.0",
    "raven-js": "^3.27.2",
    "rxjs": "^6.6.7",
    "sockjs-client": "^1.6.1",
    "stompjs": "^2.3.3",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.13.8",
    "@angular-eslint/eslint-plugin": "^0.8.0-beta.7",
    "@angular/cli": "7.3.8",
    "@angular/compiler-cli": "7.2.13",
    "@angular/language-service": "7.2.7",
    "@compodoc/compodoc": "^1.1.23",
    "@types/jasmine": "^2.8.23",
    "@types/jasminewd2": "^2.0.13",
    "@types/node": "^6.14.13",
    "@types/stompjs": "^2.3.9",
    "@typescript-eslint/eslint-plugin": "^4.33.0",
    "@typescript-eslint/eslint-plugin-tslint": "^4.33.0",
    "@typescript-eslint/parser": "^4.33.0",
    "acorn": "^6.4.2",
    "codelyzer": "^4.5.0",
    "electron": "^3.1.13",
    "eslint": "^7.30.0",
    "eslint-plugin-sonar": "^0.6.1",
    "jasmine-core": "~2.8.0",
    "jasmine-reporters": "~2.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "~0.2.2",
    "protractor": "^6.0.0",
    "protractor-jasmine2-screenshot-reporter": "~0.4.0",
    "sonarqube-scanner": "^2.9.1",
    "ts-node": "~4.1.0",
    "typescript": "3.7.7"
  }
}

**Comment by jridgewell** [comment]
The error is `No matching version found for @jridgewell/trace-mapping@^0.3.24`. I don't know what's going on with your local setup, but v0.3.24 [definitely exists](https://www.npmjs.com/package/@jridgewell/trace-mapping/v/0.3.24). There's nothing actionable for me to do here.
