### ISSUE TITLE
maybe, the latest version has a bug...

### ISSUE THREAD

**Issue by mycoin** [jridgewell/trace-mapping#4]
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/1845440/164147992-520ec62b-a6f1-40a6-bda8-f4beafa19d2e.png">

**Comment by jridgewell** [comment]
Yes, I'm trying to fix now. I'll revert on npm for the time being.

**Comment by jridgewell** [comment]
Fixed with [v0.3.7](https://github.com/jridgewell/trace-mapping/releases/tag/v0.3.7)

**Comment by mycoin** [comment]
Nice!
