### ISSUE TITLE
`sections` support

### ISSUE THREAD

**Issue by cspotcode** [jridgewell/trace-mapping#5]
Following along with several issues elsewhere on github, and would like to use trace-mapping as a (transitive) dependency in ts-node.

https://github.com/terser/terser/pull/1164#issuecomment-1068354694
Am I understanding correctly, that this library is missing support for `sections`?  Can this issue be used for tracking progress on that?

**Comment by jridgewell** [comment]
It's implemented via [`AnyMap`](https://github.com/jridgewell/trace-mapping/blob/8db5df070b15e2a669277b710a9d69ad0676524d/src/any-map.ts#L18). I hadn't documented it because I considered it to be a niche API, but I'd be happy to accept a doc PR if you want to contribute.

**Comment by cspotcode** [comment]
I see, does this mean consumers of the API must take special care to leverage it?  Or can a consumer use the API as they otherwise would?  I'm admittedly unfamiliar with `sections` and what it means.  I naively assume that consumers of this API don't necessarily need to care whether or not a sourcemap uses `sections`.

**Comment by jridgewell** [comment]
> I naively assume that consumers of this API don't necessarily need to care whether or not a sourcemap uses `sections`.

Correct. `AnyMap` can take any form of sourcemap, and will return a regular `TraceMap` instance. Eg, if a regular sourcemap is passed to `AnyMap`, it [immediately returns](https://github.com/jridgewell/trace-mapping/blob/8db5df070b15e2a669277b710a9d69ad0676524d/src/any-map.ts#L22) with a new `TraceMap`, and if a sectioned sourcemap is passed, it [converts](https://github.com/jridgewell/trace-mapping/blob/8db5df070b15e2a669277b710a9d69ad0676524d/src/any-map.ts#L24-L48) from the section offsets into a regular sourcemap and returns that as a new `TraceMap`.

**Comment by cspotcode** [comment]
Nice, thanks for the explanation.  I hope to have time to try it soon.
